// Retention: 7 years per MAS financial record requirements
// NOTE: @aoa/shared-types defines a simpler DecisionRecord with 'ESCALATED' outcome.
// This compliance-layer schema uses 'HELD' (regulatory hold) and adds metadata field.
// The compliance schema is the authoritative type for the immutable decision record plane.

/**
 * Outcome of a financial decision.
 * - APPROVED: Transaction/action permitted
 * - REJECTED: Transaction/action denied
 * - HELD: Transaction/action suspended pending review (regulatory hold)
 */
export type DecisionOutcome = "APPROVED" | "REJECTED" | "HELD";

/**
 * Immutable decision record — the audit plane that spans ALL layers
 * (policy, risk, settlement, dispute). Once written, NEVER modified.
 *
 * "If it isn't in the decision record, it didn't happen."
 */
export interface DecisionRecord {
  /** Unique identifier (UUID v4, auto-generated) */
  readonly id: string;
  /** Distributed trace ID — links record to the originating request */
  readonly trace_id: string;
  /** Agent that made the decision */
  readonly agent_id: string;
  /** Full input state snapshot at decision time (JSON) */
  readonly input_snapshot: Record<string, unknown>;
  /** Semantic version of the policy ruleset used */
  readonly policy_version: string;
  /** ML/LLM model version used, if applicable */
  readonly model_version: string | null;
  /** List of reason codes explaining the decision */
  readonly reason_codes: string[];
  /** Decision outcome */
  readonly outcome: DecisionOutcome;
  /** Actor ID if decision was manually overridden */
  readonly override_actor: string | null;
  /** ISO 8601 timestamp — auto-set at creation, immutable */
  readonly created_at: string;
  /** Arbitrary metadata (JSON) for layer-specific context */
  readonly metadata: Record<string, unknown>;
}

/**
 * Input for creating a new DecisionRecord.
 * id and created_at are auto-generated by the service.
 */
export interface DecisionRecordInput {
  trace_id: string;
  agent_id: string;
  input_snapshot: Record<string, unknown>;
  policy_version: string;
  model_version?: string | null;
  reason_codes: string[];
  outcome: DecisionOutcome;
  override_actor?: string | null;
  metadata?: Record<string, unknown>;
}

/** Query options for time-range filtering */
export interface DecisionQueryOptions {
  from?: Date;
  to?: Date;
}
